incremental test flow: update to do incremental builds

diff --git a/.github/workflows/run_tests_incremental.yml b/.github/workflows/run_tests_incremental.yml
--- a/.github/workflows/run_tests_incremental.yml
+++ b/.github/workflows/run_tests_incremental.yml
@@ -1,7 +1,7 @@
 # Syntax reference:
 # https://help.github.com/en/actions/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions
 
-name: Shadow Tests
+name: Shadow Tests Incremental
 permissions: read-all
 
 defaults:
@@ -13,6 +13,16 @@ on:
     branches: [main]
   pull_request:
     types: [opened, synchronize]
+  workflow_dispatch:
+    inputs:
+      build:
+        description: "Build new Docker images"
+        type: boolean
+        default: false
+      push:
+        description: "Push Docker images"
+        type: boolean
+        default: false
 
 env:
   CARGO_TERM_COLOR: always
@@ -23,13 +33,6 @@ jobs:
     # minimum supported kernel version in documentation when changing)
     # https://github.com/actions/virtual-environments
     runs-on: ubuntu-18.04
-    container:
-      image: ${{ matrix.container }}
-      # the default shm-size for ubuntu:18.04, but with the size increased from
-      # 65536k. github's default docker seccomp policy seems to disallow
-      # process_vm_readv and process_vm_writev; disable it altogether. See
-      # https://docs.docker.com/engine/security/seccomp/
-      options: '--shm-size="1g" --security-opt seccomp=unconfined'
     strategy:
       matrix:
         container:
@@ -79,34 +82,43 @@ jobs:
           # See https://github.com/shadow/shadow/issues/2166
           ref: ${{ github.event.pull_request.head.sha }}
 
-      - name: Get month
-        id: get-month
-        run: |
-          echo "::set-output name=month::$(/bin/date -u "+%Y%m")"
-
-      - name: Install dependencies
-        run: |
-          . ci/container_scripts/install_deps.sh
-          . ci/container_scripts/install_extra_deps.sh
-          echo "$HOME/.cargo/bin" >> $GITHUB_PATH
-
-      - name: Restore cargo registry cache
-        uses: actions/cache@v3
-        with:
-          path: |
-            ~/.cargo/registry/index/
-            ~/.cargo/registry/cache/
-            ~/.cargo/git/db/
-          # invalidate the cache once per month
-          key: cargo-registry-${{ steps.get-month.outputs.month }}
-          restore-keys: |
-            cargo-registry-
-
-      - name: Build
-        run: . ci/container_scripts/build_and_install.sh
-
       - name: Test
-        run: . ci/container_scripts/test.sh
+        run: |
+          FLAGS=()
+          FLAGS+=("-c" "${{ matrix.container }}")
+          FLAGS+=("-C" "${{ matrix.cc }}")
+          FLAGS+=("-b" "${{ matrix.buildtype }}")
+
+          # Get the generated tag for the image
+          IMAGETAG=`ci/run.sh -t ${FLAGS[@]}`
+
+          if [ "${{ github.event.inputs.build}}" == "true" ]
+          then
+            # Build the image
+            FLAGS+=("-i")
+
+            # Fetch the base image for the build.
+            # Do this before logging in to avoid charging our account for the pull.
+            docker pull ${{ matrix.container }}
+          else
+            # Ensure the image is actually available
+            if ! docker pull "${IMAGETAG}"
+            then
+              echo "Couldn't pull image; building"
+              FLAGS+=("-i")
+            fi
+          fi
+
+          if [ "${{ github.event.inputs.push}}" == "true" ]
+          then
+            FLAGS+=("-p")
+
+            # Log in so that we can push
+            docker login -u shadowsim --password "${{ secrets.DOCKERHUB_TOKEN }}"
+          fi
+
+          # Run
+          ci/run.sh ${FLAGS[@]}
 
       - name: Compress logs
         if: failure()
