incremental test flow: update to do incremental builds

diff --git a/.github/workflows/run_tests_incremental.yml b/.github/workflows/run_tests_incremental.yml
--- a/.github/workflows/run_tests_incremental.yml
+++ b/.github/workflows/run_tests_incremental.yml
@@ -1,7 +1,7 @@
 # Syntax reference:
 # https://help.github.com/en/actions/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions
 
-name: Shadow Tests
+name: Shadow Tests Incremental
 permissions: read-all
 
 defaults:
@@ -13,6 +13,12 @@ on:
     branches: [main]
   pull_request:
     types: [opened, synchronize]
+  workflow_dispatch:
+    inputs:
+      build_and_push:
+        description: "Build and push new Docker images"
+        type: boolean
+        default: false
 
 env:
   CARGO_TERM_COLOR: always
@@ -23,13 +29,6 @@ jobs:
     # minimum supported kernel version in documentation when changing)
     # https://github.com/actions/virtual-environments
     runs-on: ubuntu-18.04
-    container:
-      image: ${{ matrix.container }}
-      # the default shm-size for ubuntu:18.04, but with the size increased from
-      # 65536k. github's default docker seccomp policy seems to disallow
-      # process_vm_readv and process_vm_writev; disable it altogether. See
-      # https://docs.docker.com/engine/security/seccomp/
-      options: '--shm-size="1g" --security-opt seccomp=unconfined'
     strategy:
       matrix:
         container:
@@ -79,52 +78,59 @@ jobs:
           # See https://github.com/shadow/shadow/issues/2166
           ref: ${{ github.event.pull_request.head.sha }}
 
-      - name: Get month
-        id: get-month
-        run: |
-          echo "::set-output name=month::$(/bin/date -u "+%Y%m")"
-
-      - name: Install dependencies
-        run: |
-          . ci/container_scripts/install_deps.sh
-          . ci/container_scripts/install_extra_deps.sh
-          echo "$HOME/.cargo/bin" >> $GITHUB_PATH
-
-      - name: Restore cargo registry cache
-        uses: actions/cache@v3
-        with:
-          path: |
-            ~/.cargo/registry/index/
-            ~/.cargo/registry/cache/
-            ~/.cargo/git/db/
-          # invalidate the cache once per month
-          key: cargo-registry-${{ steps.get-month.outputs.month }}
-          restore-keys: |
-            cargo-registry-
-
-      - name: Build
-        run: . ci/container_scripts/build_and_install.sh
-
       - name: Test
-        run: . ci/container_scripts/test.sh
+        run: |
+          # Get the generated tag for the image
+          IMAGETAG=`ci/run.sh -t -c "${{ matrix.container }}" -C "${{ matrix.cc }}" -b "${{ matrix.buildtype }}"`
+
+          EXTRAFLAGS=()
+
+          if [ "${{ github.event.inputs.build_and_push }}" == "true" ]
+          then
+            # Build the image
+            EXTRAFLAGS+=("-i")
+
+            # Push the iamge
+            EXTRAFLAGS+=("-p")
+
+            # Fetch the base image for the build.
+            # Do this before logging in to avoid charging our account for the pull.
+            docker pull ${{ matrix.container }}
+
+            # Log in so that we can push
+            # FIXME: user
+            docker login -u sporksmith --password "${{ secrets.DOCKERHUB_TOKEN }}"
+          else
+            # Try to pull the image
+            if ! docker pull "${IMAGETAG}"
+            then
+              echo "Couldn't pull image; building"
+
+              # Build, but don't push
+              EXTRAFLAGS+=("-i")
+            fi
+          fi
+
+          # Run
+          ci/run.sh ${EXTRAFLAGS[@]} -c "${{ matrix.container }}" -C "${{ matrix.cc }}" -b "${{ matrix.buildtype }}"
 
       - name: Compress logs
         if: failure()
         run: |
           shopt -s globstar
-          tar -cJf build/Testing/Temporary{.tar.xz,/}
-          for f in build/**/*.data; do tar -cJf "$f.tar.xz" "$f/"; done
+          tar -cJf cibuild/Testing/Temporary{.tar.xz,/}
+          for f in cibuild/**/*.data; do tar -cJf "$f.tar.xz" "$f/"; done
 
       - name: Upload shadow data directories
         uses: actions/upload-artifact@v3
         if: failure()
         with:
           name: shadow-data-dirs
-          path: build/**/*.data.tar.xz
+          path: cibuild/**/*.data.tar.xz
 
       - name: Upload shadow log file
         uses: actions/upload-artifact@v3
         if: failure()
         with:
           name: shadow-log-file
-          path: build/Testing/Temporary.tar.xz
+          path: cibuild/Testing/Temporary.tar.xz
